### ISSUE TITLE
Error when a TD is not found

### ISSUE THREAD

**Issue by manuelleduc** [kevoree/generator-kevoree#3]
When the user tries to create a component from an existing TD, if it search does not return a result the resulting message looks like a stack trace, which is not really ergonomic

**Comment by manuelleduc** [comment]
➜  kevoree-js-comp-avatarjs  yo kevoree                            

Kevoree Project Generator:

[?] Would you like to start from an existing TypeDefinition from the Kevoree Registry? Yes
[?] Specify a TypeDefinition fully qualified name (eg. Ticker or my.company.MyType) LoL
/home/mleduc/.nvm/versions/node/v4.2.6/lib/node_modules/generator-kevoree/app/index.js:158
                        throw err;
                        ^

Error: Unable to find "org.kevoree.library.LoL" on Kevoree registry
    at ClientRequest.<anonymous> (/home/mleduc/.nvm/versions/node/v4.2.6/lib/node_modules/generator-kevoree/node_modules/kevoree-registry-client/lib/get.js:100:26)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)

**Comment by manuelleduc** [comment]
https://github.com/kevoree/generator-kevoree/commit/351f171d1bce6c9064015598eb6195e1e1346b0a
